### ISSUE TITLE
Performance issue when working with many points

### ISSUE THREAD

**Issue by tracek** [randyzwitch/streamlit-folium#125]
The time it takes for `st_folium` to return with `returned_objects` seems to be proportional to the number of objects displayed on the map. I am plotting many markers and lines, but in the end I am only interested in the point that the user has clicked, i.e.

```
st_data = st_folium(m, returned_objects=["last_object_clicked"])
```
The trouble is, with many points it can take e.g. 10 seconds to return. If I make the map static, it's nearly instant.

Is there anything I can do to improve the performance, short of reducing the number of points?

**Comment by randyzwitch** [comment]
I think it has to be proportional, since we're passing the data from the browser to Python. So `returned_objects=["last_object_clicked"]` can only be evaluated when the data exists in Python.

It _might be_ the case that we can pass an Arrow buffer back to Python (if we're not already), but even that would likely have the same proportionality issue (though, as binary instead of JSON)

**Comment by BastienGauthier** [comment]
For information, I think I experienced a similar problem, even if I set returned_objects = [] (with 5000+ markers and lines). I would expect to go back to the static performance in this case.

**Comment by randyzwitch** [comment]
I'm fairly certain that the replace is necessary, as otherwise the page will re-render in Streamlit every time (which is the original performance issue I believe that solves).

I do wonder if there is any performance gain from setting `count=1` in the replace function; @blackary, if I'm thinking about this correctly, these are searching across the keys. You'd still replace once per loop, but at least we could short-circuit out of the loop once the key is found?

**Comment by BastienGauthier** [comment]
Excellent, thank you ! I will test this as soon as possible !
