### ISSUE TITLE
[Issue] When using st_folium, a blank space will be left below the map

### ISSUE THREAD

**Issue by leons1982** [randyzwitch/streamlit-folium#198]
*Issue Desc*: When I use st_folium on the latest version of streamlit, after the map is rendered, a large blank area is left at the bottom of the map
*Issue Image*: <img width="707" alt="image" src="https://github.com/randyzwitch/streamlit-folium/assets/76804916/3ce45be7-4917-46b9-ae0c-f207e996971b">

*Versions I used*:
* streamlit:1.36.0
* streamlit-folium:0.21.0
* folium:0.17.0

*Code to reproduce the issue*:
```python
import folium
import streamlit as st
from streamlit_folium import st_folium

m = folium.Map(location=[39.949610, -75.150282], zoom_start=5)

with st.container(border=True):
    st_folium(m, height=500)
```

*Additional information*:
When I use the `folium_static` function, the map can be rendered normally without any white blank area, but I need to get the information returned by the map, so I need to use `st_folium`

**Comment by randyzwitch** [comment]
It's not immediately obvious what the issue might be, but if this only happens when you upgrade the Streamlit version, you might try filing a bug with them as well? I can't think of a change we've made recently that would affect the underlying container (the code of which comes from Streamlit as part of the custom components functionality)

**Comment by leons1982** [comment]
Ok,I will report the issue the streamlit team too, thanks.

**Comment by egelados** [comment]
Also waiting for a solution to this as well

**Comment by egelados** [comment]
Possible solution
-----------------

After many hours of trial and errors effort i ended up with a few conclusions:
1) it has to be indeed an issue of streamlit's component handling. 
2) The problem appears on random conditions and is probably cache related since it never happens after Ctrl+F5 refresh.


Gladly i seem to have found a solution!! The problem seems to go away if you: 

1) containerize the map in a fixed height container (greater that 700pixels)
2) call st_folium with parameter use_container_width=True


Here is an example:

map_cont = st.container(height=735, border=True)
with map_cont:
    # Initialize the map
    fancymap = folium.Map(location=[40.42,23.58], tiles="OpenStreetMap", zoom_start=8)
    ...
    ...
    ...
    # Display the freaking fancy map
    st_folium(fancymap, use_container_width=True)


I m using:
folium==0.17.0
streamlit_folium==0.21.1
streamlit==1.36.0

Please let me know if this helps or something related comes up

**Comment by randyzwitch** [comment]
Thanks for exploring @egelados! I'm going to close this issue since it appears upstream, and we have no ability to code in this sort of fix into the package.
