### ISSUE TITLE
Infinite Reload Issue with st_folium Function (Does Not Occur with folium_static)

### ISSUE THREAD

**Issue by yuuma0207** [randyzwitch/streamlit-folium#239]
# Summary
When using the `st_folium` function to render a Folium map in Streamlit, **adding random jitter** to marker positions to prevent overlap causes the app to enter an infinite reload loop.

# Steps to Reproduce
The issue can be reproduced with the following code:
```python
import streamlit as st
import pandas as pd
import numpy as np
import folium
from streamlit_folium import st_folium

def load_data():
    return pd.DataFrame({
        "id": ["A", "B", "C"],
        "lat": [38.260, 38.280, 38.270],
        "lon": [140.882, 140.850, 140.870]
    })

df = load_data()
df_copy = df.copy()

# Initial map setup
sendai_st = [38.2682, 140.8694]
m = folium.Map(location=sendai_st, zoom_start=13)

# create random position
jitter_factor = 0.1
df_copy['lat'] += np.random.uniform(-jitter_factor, jitter_factor, size=len(df))
df_copy['lon'] += np.random.uniform(-jitter_factor, jitter_factor, size=len(df))

# Add markers to the map
for _, row in df_copy.iterrows():
    folium.Marker(
        location=[row["lat"], row["lon"]],
        popup=row["id"],
        icon=folium.Icon(color='red', icon='info-sign')
    ).add_to(m)

# Streamlit layout
st.header("Check Marker Positions")
st_folium(m, width=1000, height=700)

```

# Actual Behavior
When the code is executed, the Streamlit app enters an infinite reload loop. No error messages are displayed in the logs, but the app becomes unusable.

# Expected Behavior
The map should render correctly, and the app should not reload indefinitely, even when random jitter is added to marker positions.

# Environment Information
OS: [macOS 15.0.1]
Browser: [Chrome 131]
Python Version: [3.12.4]
Streamlit Version: [1.40.2]
streamlit-folium Version: [0.23.0]
Folium Version: [0.18.0]

# Additional Information
This issue occurs only when using the `st_folium` function. The problem does not occur when using the `folium_static`. It might be related to how `st_folium` manages state updates.

**Comment by randyzwitch** [comment]
This would be the expected behavior in this case. Because you have a random component outside of an `st.cache`, every time Streamlit runs top-to-bottom, you will re-run that line of code. When the map gets rendered, then it will check the hash, they won't match, and the map will re-render. And this will happen indefinitely.

I would write a function `add_jitter(df): ` that takes the dataframe in and returns a dataframe. Because the input `df` wouldn't change, when you apply the random jitter inside the function, it shouldn't run indefinitely. Streamlit will see the function signature didn't change and returned the cached data.
