### ISSUE TITLE
change color of maker on click in examples/interactive_app.py

### ISSUE THREAD

**Issue by raybellwaves** [randyzwitch/streamlit-folium#67]
Nice project.

in https://share.streamlit.io/randyzwitch/streamlit-folium/examples/interactive_app.py would be cool to have some way of changing color of the marker on click.

Motivation is my college @wxman22 would like to use the dashboard to plan his next foray into a national park. We said it would be cool if you could click on a marker and indicate you have been to that park (e.g. change the color of the marker, maybe make it have a strikethrough?) so that he is left to decide which national park to enjoy next.

**Comment by blackary** [comment]
You could totally do that, but you would need to connect to a database of some sort to keep track of the clicks, because otherwise it would get reset every time you visited the app. My recommendations would be either supabase or google sheets, because they’re both free and relatively easy to use. There are guides to both here https://docs.streamlit.io/knowledge-base/tutorials/databases.

Once you have a database to track your clicks, you can essentially use interactive app as-is, just add some code under [this line](https://github.com/randyzwitch/streamlit-folium/blob/master/examples/interactive_app.py#L112) to update the database  and then change [this part](https://github.com/randyzwitch/streamlit-folium/blob/master/examples/interactive_app.py#L95) to pass in the appropriate color (you would probably need to use a custom [Icon](https://python-visualization.github.io/folium/modules.html#folium.map.Icon) to change the color)

That may be a bit out of the scope of this plugin to demonstrate that, but if you end up building that, please share!

**Comment by randyzwitch** [comment]
Closing, since this is less of a library issue and more of a potential demo that could exist
