### ISSUE TITLE
Feature Request : Don't generate new data on double Click

### ISSUE THREAD

**Issue by djouallah** [randyzwitch/streamlit-folium#78]
is there a way to disable generating new variable when a user Double click for Zooming ?

**Comment by djouallah** [comment]
here is the link to my app, basically, I generate a new query when the user click on the map, double clicking generate a lot of extra queries which are not needed 
https://github.com/djouallah/streamlit_gis/blob/main/app.py

**Comment by randyzwitch** [comment]
I would solve this using `st.button` with a "Refresh data" or "Fetch data" label, so that you're only retrieving data when the person clicks the button. But as a general pattern, I'm not sure how logical it would be to have the bounding box shown on the screen not reflect what Python thinks the bounding box is

**Comment by djouallah** [comment]
thanks :)

**Comment by blackary** [comment]
@djouallah Can you try passing `folium.Map(double_click_zoom=False)` and see if that gives you the behavior you were looking for?
