### ISSUE TITLE
Use Folium attribute selection to populate ST controls

### ISSUE THREAD

**Issue by ymoisan** [randyzwitch/streamlit-folium#8]
Hi Randy.  I have created a user story for a use case I have which is to use information from selected features in a specific map layer to populate ST controls.  An example : populating an image list in a ST dropdown with the currently visible (or selected) features on a given layer in the map.

I'd like to work on a PR for that and wondered if you had thoughts or plans along those lines.  Here is the (short) document : https://github.com/ymoisan/streamlit-folium/blob/master/user-stories.md.  Comments welcome.  Thanx for the component !

**Comment by randyzwitch** [comment]
Thanks for checking out this component!

There are really two parts here:

1) Folium itself isn't bi-directional, so any work to pass data back and forth would need to be done at the leaflet layer

2) Deciding what to pass back and forth

Number 1 can be done independently of number 2, since you could set up a bi-directional component for Streamlit that doesn't return anything. That could be a good first project for anyone.

For number 2, we'd have to think of the entire surface area of plugins that people might use from Folium, and then think about passing data back. I suspect what we would want to do is pass a Dict back to Python, so that we can have any number of keys returned back (where the key might be a plugin, or a specific value like `bbox`). Then, it's a matter of implementing all those things.

If you're willing to take a shot at a PR, I'm happy to review it!

**Comment by ymoisan** [comment]
Thanx for your ideas.  I agree that a broad approach assessing plugins should be taken for the general case.  I noticed for example that the `Fullscreen` plugin does not work currently through Streamlit-folium.

I started playing with html (e.g. adding a map title) to feel things a bit more.  We'll see what we'll com up with.

**Comment by dansbecker** [comment]
It looks like #9 is a step in this direction... does that suggest there's a workaround for item 1 @randyzwitch mentioned (Folium not bi-directional)?

If the goal is to change what data is used in a graph based on the marker a user selects in a folium map, would you still suggest using leaflet? Or does #9 look like something that will be a viable path in the next couple months?

**Comment by randyzwitch** [comment]
Hi @dansbecker - 

Yes, #9 is a step towards have data communicate back and forth, but it's not going to be because Folium does it. Rather, I was originally going to set it up to pass the bounding box back from Leaflet.js to Python, just to prove it could be done. Then, we could figure out what other data might be useful to send back.

Not sure when I'll get back to working on that PR, but the fix I was waiting for has gone into base Streamlit, so if I can get a co-worker to help me it might not be too long from now.

**Comment by ymoisan** [comment]
@randyzwitch After some time experimenting with streamlit-folium, we did a quick try with a pure Leaflet (and React) implementation instead because of one particularly thorny issue we could not overcome : leave the map "alone" when updating a Streamlit item.  I still very much like the idea of avoiding JS and staying in Python (being able to use tools like shapely is great, for example) but the way Streamlit re-runs the whole script from top to bottom upon refreshing one UI component makes it unbearable because it re-creates the map every time.  At least I haven't found a decent way to cache the map (it does not appear to be "st.cacheable").

I was (and still am) attracted by the simplicity of Streamlit but as far as I can see it looks like using it as a "web map wrapper" may not be the best use case.  Still searching ...

**Comment by randyzwitch** [comment]
That's a good point, and glad you are researching this. As a non-Folium user for the most part, I'm viewing this as an interesting exploration of what Streamlit and the relation between Python and JS might be.

Which is to say, the actual Python Folium part is limited by the Folium package itself. Bi-directional communication doesn't exist there, so it doesn't easily exist in Streamlit. But if we're viewing Folium as a _API_ to Leaflet.js, in the same way that Vega is a grammar of D3, then there might be some interesting ideas here.

**Comment by randyzwitch** [comment]
Version 0.6.0 is now on PyPI. Use `pip install -U streamlit-folium` to get the latest version. Please also see the release notes on how this version is believed to solve this issue

https://github.com/randyzwitch/streamlit-folium/releases/tag/v0.6.0
