### ISSUE TITLE
Projection

### ISSUE THREAD

**Issue by SpencerMartel** [randyzwitch/streamlit-folium#87]
Thanks for the great library, it's awesome.

Quick question, what is the projection of the coords passed back from the last clicked component?

**Comment by randyzwitch** [comment]
I suspect WGS84, but I don’t know for certain. Maybe @blackary knows?On Oct 29, 2022, at 11:45 AM, Spencer Martel ***@***.***> wrote:﻿
Thanks for the great library, it's awesome.
Quick question, what is the projection of the coords passed back from the last clicked component?

**Comment by SpencerMartel** [comment]
No sweat, the last_clicked passes back longitude values that don't exist. Longitudes are between -180 and 180 but if you move the map to the "right" the lat values do not reset and you can increase them infinitely. Any idea why this happens?

**Comment by blackary** [comment]
@SpencerMartel By default Folium uses EPSG3857, but you can pass a different one via the `crs` argument -- https://python-visualization.github.io/folium/modules.html#folium.folium.Map

Thanks for the note about the longitude values that don't exist -- I'll look into that.

**Comment by blackary** [comment]
@SpencerMartel I haven't found any clean way in Folium or Leaflet for automatically wrapping all longitudes to [-180, 180], so I'll probably leave this as-is for now. 

If you want to restrict the map to that longitude range so that the user can't unintentionally end up on another copy of the world map, you can use `max_bounds`, like 
```python
m = folium.Map(
    location=[39.949610, -75.150282], zoom_start=5, max_bounds=[[-180, -90], [180, 90]]
)
```
